development:
  url: <%= "postgresql://development:development@localhost:5432/scrumpoher_development" %>

test:
  url: <%= "postgresql://development:development@localhost:5432/scrumpoher_test" %>

production:
  url: <%= ENV['DATABASE_URL'] %>
